services:
  db:
    container_name: intro_sql
    image: postgres:15.1
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    user: "${UID}:${GID}"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80" 
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin